SET SERVEROUTPUT ON

--CREACION DE USUARIOS
CREATE USER "RONNY" IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;

-- ROLES
GRANT "CONNECT" TO RONNY;

-- PRIVILEGIOS
REVOKE ALTER TABLESPACE FROM "RONNY";
REVOKE DROP ANY TRIGGER FROM "RONNY";

-- CREACION DE TABLAS
-- TABLAS CATALOGO
CREATE TABLE PERSONAS(
COMMENT ON TABLE "RONNY"."PERSONAS" IS 'TABLA PARA IDENTIFICAR SI LA PERSONA ES DOCTOR, PACIENTE, EMPLEADO'
DUI VARCHAR(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."DUI" IS 'CAMPO PRIMARIO DE LA TABLA Y SIRVE PARA IDENTIFICAR A LA PERSONAS'
Nombre VARCHAR2(20) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."NOMBRE" IS 'CAMPO PARA EL NOMBRE DE LAS PERSONAS'
Fecha_nacimiento DATE NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."FECHA_NACIMIENTO" IS 'CAMPO PARA SABER LA FEHCA DE NACIMIENTO DE LAS PERSONAS'
Genero CHAR(1) CONSTRAINT CH_GENERO CHECK(GENERO IN ('M','F')) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."GENERO" IS 'CAMPO PARA SABER EL GENERO DE LAS PERSONAS '
E_mail VARCHAR2(20) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."E_MAIL" IS 'CAMPO PARA EL EMAIL DE LAS PERSONAS'
Telefono_celular VARCHAR2(12) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."TELEFONO_CELULAR" IS 'CAMPO PARA EL CELULAR DE LAS PERSONAS'
Tipo_persona VARCHAR2(20) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."TIPO_PERSONA" IS 'ESTE CAMPO SIRVE PARA SABER EN EL SISTEMA SI LA PERSONA ES DOCTOR, PACIENTE, EMPLEADO '
Estado VARCHAR2(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."PERSONAS"."ESTADO" IS 'CAMPO PARA SABER SI EL USUARIO ESTA ACTIVO O INACTIVO'
Rol_usuario VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."PERSONAS"."ROL_USUARIO" IS 'CAMPO PARA DEFINIR EN EL SISTEMA SI ES DOCTOR, PACIENTE, EMPLEADO '
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."PERSONAS"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."PERSONAS"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."PERSONAS"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."PERSONAS"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_DUI 
PRIMARY KEY(DUI)
);

/*
COMMENT DE LA TABLA PERSONAS
*/

SELECT * FROM USER_TAB_COMMENTS;
SELECT * FROM USER_COL_COMMENTS;

SELECT * FROM DICTIONARY;

CREATE TABLE TIPO_EXAMEN(
COMMENT ON TABLE "RONNY"."TIPO_EXAMEN" IS 'TABLA PARA SABER LOS TIPOS DE EXAMEN DEL LABORATORIO CLINICO'
idtipoExamen NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."IDTIPOEXAMEN" IS 'CAMPO PARA EL ID DE CADA EXAMEN'
NOMBRE_EXAMEN VARCHAR2(50) NOT NULL,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."NOMBRE_EXAMEN" IS 'CAMPO PARA SABER EL NOMBRE DE LOS EXAMENES DEL LABORATORIO CLINICO'
MUESTRA VARCHAR2(255) NOT NULL,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."MUESTRA" IS 'CAMPO PARA SABER LA MUESTRA DEPENDIENDO DEL EXAMEN A REALIZAR'
DESCRIPCION VARCHAR2(255) NOT NULL,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."DESCRIPCION" IS 'CAMPO PARA UNA DESCRIPCION DEL EXAMEN '
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."TIPO_EXAMEN"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDTIPOEXAMEN
PRIMARY KEY(idtipoExamen)
);

CREATE TABLE ENCABEZADO_EXAMEN(
COMMENT ON TABLE "RONNY"."ENCABEZADO_EXAMEN" IS 'ESTA TABLA ES PARA CONOCER EL ENCABEZADO DEL EXAMEN'
IDENCABEZADOEXA NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."IDENCABEZADOEXA" IS 'CAMPO PARA CONOCER EL ENCABEZADO DEL ID DEL EXAMEN'
DESCRIPCION VARCHAR2(200) NOT NULL,
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."DESCRIPCION" IS 'CAMPO PARA LA DESCRIPCION DEL EXAMEN'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."ENCABEZADO_EXAMEN"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDENCABEZADOEXA
  PRIMARY KEY(IDENCABEZADOEXA)
);

-- TABLAS TRANSACCIONALES


CREATE TABLE EXAMENESREALIZADOS (
COMMENT ON TABLE "RONNY"."EXAMENESREALIZADOS" IS 'ESTA TABLA ES PARA CONOCER LOS EXAMENES REALIZADOS DEL LABORATORIO CLINICO'
IDEXAMEN_REALIZADO NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."IDEXAMEN_REALIZADO" IS 'CAMPO PARA CONOCER EL ID DEL EXAMEN REALIZADO DEL LABORATORIO CLINICO'
DUI VARCHAR(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."DUI" IS 'CAMPO PARA CONOCER EL DUI DEL PACIENTE QUE SE REALIZO EL EXAMEN'
IDTIPOEXAMEN NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."IDTIPOEXAMEN" IS 'CAMPO PARA CONOCER EL ID DEL EXAMEN QUE SE REALIZO'
FECHA DATE NOT NULL,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."FECHA" IS 'CAMPO PARA CONOCER LA FEHCA EN LA QUE SE REALIZO EL EXAMEN'
PRECIO NUMBER(4,2) NOT NULL,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."PRECIO" IS 'CAMPO PARA CONONCER EL PRECIO DEL EXAMEN A RELIZAR'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."EXAMENESREALIZADOS"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDEXAMENREALIZADO
PRIMARY KEY(IDEXAMEN_REALIZADO)
);

CREATE TABLE CABECERA_HISTORIAL(
COMMENT ON TABLE "RONNY"."CABECERA_HISTORIAL" IS 'ESTA TABLA ES PARA CONCER A QUIEN PERTENECE EL HISTORIAL DE EXAMENES'
IDCABECERA NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."IDCABECERA" IS 'LLAVE PRIMARIA DE CORRELATIVO'
DUI VARCHAR(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."DUI" IS 'CAMPO PARA EL DUI DEL PACIENTE QUE VA IR EN LA CABECERA DEL EXAMEN'
FECHA_APERTURA DATE NOT NULL,
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."FECHA_APERTURA" IS 'FEHCA EN EL QUE EMPIEZA EL HISTORIAL DEL PACIENTE'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."CABECERA_HISTORIAL"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDCABECERA
PRIMARY KEY(IDCABECERA)
);


CREATE TABLE DETALLE_HISTORIAL(
COMMENT ON TABLE "RONNY"."DETALLE_HISTORIAL" IS  'LA TABLA ES PARA CONOCER TODOS LOS DETALLES DEL HISTORIAL DE LOS EXAMENES DEL PACIENTE'
ID_DETALLEHIST NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."ID_DETALLEHIST" IS  'CAMPO DE ID PARA EL DETALLE DEL HISTORIAL'
IDCABECERA NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."IDCABECERA" IS  'LLAVE FORANEA, CAMPO PARA LLAMAR ID DE ID PARA LA CABECERA'
DUI VARCHAR(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."DUI" IS  'LLAVE FORANEA, CAMPO PARA LLAMAR EL DUI DEL PACIENTE'
FECHA_REALIZADO DATE NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."FECHA_REALIZADO" IS  'FECHA DEL EXAMEN QUE SE REALIZO EL PACIENTE'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_HISTORIAL"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDETALLEHIS
PRIMARY KEY(ID_DETALLEHIST)
);

CREATE TABLE DETALLE_EXAMEN_REALIZA(
COMMENT ON TABLE "RONNY"."DETALLE_EXAMEN_REALIZA" IS 'TABLA PARA EL DETALLE DEL EXAMEN REALIZADO'
ID_DETALLE NUMBER (3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."ID_DETALLE" IS 'CAMPO PARA CONOCER EL ID DEL DETALLE DEL EXAMEN REALIZADO'
IDEXAMEN_REALIZADO NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."IDEXAMEN_REALIZADO" IS 'CAMPO PARA CONOCER EL ID DEL EXAMEN REALIZADO '
IDTIPOEXAMEN NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."IDTIPOEXAMEN" IS 'CAMPO PARA CONOCER EL ID DEL TIPO DE EXAMEN QUE SE REALIZO'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_EXAMEN_REALIZA"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_DETALLE_EXAMEN
PRIMARY KEY(ID_DETALLE)
);

CREATE TABLE DETALLE_TIPOEXA(
COMMENT ON TABLE "RONNY"."DETALLE_TIPOEXA" IS 'TABLA PARA CONOCER EL DETALLE DEL TIPO DEL EXAMEN'
ID_DETALLETIPO NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."ID_DETALLETIPO" IS 'CAMPO PARA CONOCER EL ID DEL DETALLE DEL TIPO DE EXAMEN QUE SE REALIZO'
IDTIPOEXAMEN NUMBER(3,0) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."IDTIPOEXAMEN" IS 'CAMPO PARA CONOCER EL ID DEL TIPO DE EXAMEN QUE SE REALIZO'
CAMPO_EXAMEN VARCHAR2(200) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."CAMPO_EXAMEN" IS 'CAMPO PARA CONOCER EL RESULTADO DEL EXAMEN'
REQUIERE_VALOR VARCHAR2(10) NOT NULL,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."REQUIERE_VALOR" IS 'CAMPO PARA SABER SI EL EXAMEN DE SANGRE REQUIERE VALOR NORMAL O NO'
VALORNORMAL VARCHAR2(200),
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."VALORNORMAL" IS 'SOLO SI REQUIERE VALOR NORMAL DE LO CONTRARIO NO ES NECESARIO'
Usuario_creo VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."USUARIO_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE INSERTO NUEVO REGISTRO '
Fecha_creo DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."FECHA_CREO" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER LA FECHA DE CUANDO SE CREO UN REGISTRO'
Usuario_modi VARCHAR2(20),
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."USUARIO_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER EL USUARIO QUE MODIFICO REGISTRO'
Fecha_modi DATE,
COMMENT ON COLUMN "RONNY"."DETALLE_TIPOEXA"."FECHA_MODI" IS 'CAMPO PARA LA TRASABILIDAD DE LA INFORMACION Y SABER CUANDO LA FECHA DE UN REGISTRO SE MODIFICA'
-- LLAVE PRIMARIA
CONSTRAINT PK_IDDETALLETIPO
PRIMARY KEY(ID_DETALLETIPO)
);

--INSERTAR POR DEFECTO UN VALOR 
/*ALTER TABLE TELEFONO
  MODIFY MARCA VARCHAR2(30) DEFAULT 'ENTER'; */


--LLAVES FORANEA EXAMENES REALIZADOS
ALTER TABLE EXAMENESREALIZADOS
ADD CONSTRAINT FK_PERSONAS
FOREIGN KEY(DUI)
REFERENCES PERSONAS(DUI);

ALTER TABLE EXAMENESREALIZADOS
ADD CONSTRAINT FK_TIPOEXAMEN0
FOREIGN KEY(IDTIPOEXAMEN)
REFERENCES TIPO_EXAMEN(IDTIPOEXAMEN);

--LLAVE FORANEA CABECERA HISTORIAL
ALTER TABLE CABECERA_HISTORIAL
ADD CONSTRAINT FK_PERSONA2
FOREIGN KEY(DUI)
REFERENCES PERSONAS(DUI);

--LLAVES FORANEAS DETALLE HISTORIAL
ALTER TABLE DETALLE_HISTORIAL
ADD CONSTRAINT FK_PERSONA3
FOREIGN KEY(DUI)
REFERENCES PERSONAS(DUI);

ALTER TABLE DETALLE_HISTORIAL
ADD CONSTRAINT FK_CABECERAHIST
FOREIGN KEY(IDCABECERA)
REFERENCES CABECERA_HISTORIAL(IDCABECERA);

--LLAVES FORANEAS DETALLE EXAMEN REALIZADO
ALTER TABLE DETALLE_EXAMEN_REALIZA
ADD CONSTRAINT FK_EXAMENREALIZA
FOREIGN KEY(IDEXAMEN_REALIZADO)
REFERENCES EXAMENESREALIZADOS(IDEXAMEN_REALIZADO);

ALTER TABLE DETALLE_EXAMEN_REALIZA
ADD CONSTRAINT FK_TIPOEXAMEN
FOREIGN KEY(IDTIPOEXAMEN)
REFERENCES TIPO_EXAMEN(IDTIPOEXAMEN);

--LLAVE FORANEA DETALLE TIPO EXAMEN
ALTER TABLE DETALLE_TIPOEXA
ADD CONSTRAINT FK_TIPOEXAMEN2
FOREIGN KEY(IDTIPOEXAMEN)
REFERENCES TIPO_EXAMEN(IDTIPOEXAMEN);

-- DICCIONARIO DE DATOS
SELECT 
X.TABLE_NAME NOMBRE_TABLA, X.COLUMN_ID POSICION, 
LLAVE,
X.COLUMN_NAME NOMBRE_COLUMNA, 
DATA_TYPE TIPO_DATO, DATA_LENGTH LONGITUD, COMMENTS COMENTARIO
FROM
(
    SELECT A.TABLE_NAME, A.COLUMN_ID, A.COLUMN_NAME,
    A.DATA_TYPE, A.DATA_LENGTH, 
    B.COMMENTS

    FROM USER_TAB_COLUMNS A
    LEFT JOIN USER_COL_COMMENTS B
    ON A.TABLE_NAME = B.TABLE_NAME
    AND A.COLUMN_NAME=B.COLUMN_NAME
    WHERE 
    A.TABLE_NAME NOT LIKE '%$%' 
    AND A.TABLE_NAME NOT LIKE 'SCHED%'
    AND A.TABLE_NAME NOT LIKE 'MVIEW%'
    AND B.COMMENTS IS NOT NULL
) X 
LEFT JOIN
(
    SELECT UC.TABLE_NAME, COLUMN_NAME, 
    CASE CONSTRAINT_TYPE 
        WHEN 'P' THEN 'PK' 
        WHEN 'R' THEN 'FK'
    END LLAVE
    FROM USER_CONSTRAINTS UC
    LEFT JOIN USER_CONS_COLUMNS UCC
    ON UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
    WHERE UC.CONSTRAINT_TYPE='P'
    OR UC.CONSTRAINT_TYPE='R'
) Y
ON X.TABLE_NAME=Y.TABLE_NAME 
AND X.COLUMN_NAME = Y.COLUMN_NAME
ORDER BY X.TABLE_NAME, X.COLUMN_ID;
